# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yaml2json < Formula
  desc "Convert YAML to JSON
"
  homepage "https://github.com/suzuki-shunsuke/yaml2json"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/yaml2json/releases/download/v0.1.1/yaml2json_darwin_arm64.tar.gz"
      sha256 "f75b22927e7d7db34b0175dac29782bdd3b2878d36cdef04c5efabb11e947b19"

      def install
        bin.install "yaml2json"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/yaml2json/releases/download/v0.1.1/yaml2json_darwin_amd64.tar.gz"
      sha256 "4e186821291b22c4989158f2d4f25d4429312a76920a5b92009527cb32b3b79f"

      def install
        bin.install "yaml2json"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/yaml2json/releases/download/v0.1.1/yaml2json_linux_amd64.tar.gz"
      sha256 "58e7857180276e85f2fc04f5780ab86b86202834db6198cae8ef388cc9293a2c"

      def install
        bin.install "yaml2json"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suzuki-shunsuke/yaml2json/releases/download/v0.1.1/yaml2json_linux_arm64.tar.gz"
      sha256 "1b3bf9e7c01ae71f52d10e9993ef3ed2258f1590d4c89805d9711b5161cc1af7"

      def install
        bin.install "yaml2json"
      end
    end
  end

  test do
    system "#{bin}/yaml2json --version"
  end
end
