# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yaml2json < Formula
  desc "Convert YAML to JSON
"
  homepage "https://github.com/suzuki-shunsuke/yaml2json"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/yaml2json/releases/download/v0.2.1/yaml2json_darwin_amd64.tar.gz"
      sha256 "dc9e271f05bbc226466142e49cc761c10b42f95c226427b47fd42c1a662b171c"

      def install
        bin.install "yaml2json"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/yaml2json/releases/download/v0.2.1/yaml2json_darwin_arm64.tar.gz"
      sha256 "700f2cb240a937289a1d9c82aed81f8929f02c378861cde56f17eb2524b430c7"

      def install
        bin.install "yaml2json"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suzuki-shunsuke/yaml2json/releases/download/v0.2.1/yaml2json_linux_arm64.tar.gz"
      sha256 "edb318f2d836ed8f73bada0ddffbe4f73886731fc3bd84f8aebf59a1c9334769"

      def install
        bin.install "yaml2json"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/yaml2json/releases/download/v0.2.1/yaml2json_linux_amd64.tar.gz"
      sha256 "123f28a73c03f002f51ee8ee870076b6941d153de4377a2759b48a770b813908"

      def install
        bin.install "yaml2json"
      end
    end
  end

  test do
    system "#{bin}/yaml2json --version"
  end
end
